apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - crd/bases/infra.loft.sh_kubevirtproviderclusters.yaml
  - manager/deployment.yaml
  - rbac/service-account.yaml
  - rbac/role.yaml
  - rbac/role-binding.yaml

